import { StyleSheet } from 'react-native'

import { responsiveSize, Colors, respFontSize, Fonts } from '@/Utils'

export const styles = StyleSheet.create({
  mainContainer: { backgroundColor: Colors.secondary, flex: 1 },
  itemSeparatorComponent: { height: responsiveSize(26) },
  threadNameView: {
    alignSelf: 'center',
    alignItems: 'center',
    marginVertical: responsiveSize(20),
    borderBottomColor: Colors.darkSilver,
    borderBottomWidth: 1,
  },
  threadNameText: {
    maxWidth: responsiveSize(350),
    color: Colors.white,
    fontFamily: Fonts.GilroyBold,
    fontSize: respFontSize(15),
    marginBottom: responsiveSize(10),
  },
  flatListView: {
    // flex: 1,
  },
  parentContainer: {
    width: responsiveSize(380),
    alignSelf: 'flex-end',
    flexDirection: 'row',
  },
  Container: {
    borderTopLeftRadius: responsiveSize(8),
    borderBottomLeftRadius: responsiveSize(8),
    borderBottomRightRadius: responsiveSize(8),
    backgroundColor: Colors.messageCardGrey,
    padding: responsiveSize(20),
    flex: 1,
  },
  repliedView: {
    padding: responsiveSize(10),
    borderColor: Colors.primary,
    borderWidth: 1,
    borderRadius: responsiveSize(7),
  },
  textMessage: {
    fontFamily: Fonts.GilroyMedium,
    color: Colors.silver,
    lineHeight: responsiveSize(25),
    fontSize: respFontSize(15),
  },
  currentUserTitle: {
    fontFamily: Fonts.GilroyBold,
    color: Colors.primary,
    fontSize: respFontSize(15),
    marginBottom: responsiveSize(8),
  },
  noteMessage: {
    fontFamily: Fonts.GilroyMedium,
    color: Colors.silver,
    lineHeight: responsiveSize(20),
    fontSize: respFontSize(12),
    paddingHorizontal: responsiveSize(10),
  },
  rightTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: responsiveSize(13),
    borderRightWidth: responsiveSize(13),
    borderBottomWidth: responsiveSize(26),
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.messageCardGrey,
    transform: [{ rotate: '90deg' }],
    marginLeft: responsiveSize(-1),
  },
  dateView: {
    alignSelf: 'flex-end',
    backgroundColor: Colors.messageCardGrey,
    paddingTop: responsiveSize(5),
  },
  dateText: {
    color: Colors.white,
    fontFamily: Fonts.Gilroy,
    fontSize: respFontSize(9),
  },
  flatListStyles: { paddingTop: responsiveSize(10) },
  textInputView: {
    marginTop: responsiveSize(10),
    marginBottom: responsiveSize(10),
    marginHorizontal: responsiveSize(20),
    justifyContent: 'space-between',
    paddingHorizontal: responsiveSize(25),
    maxHeight: responsiveSize(140),
    borderWidth: 1,
    borderRadius: responsiveSize(20),
    borderColor: Colors.messageCardGrey,
    flexDirection: 'row',
    padding: responsiveSize(5),
  },
  textInputStyles: {
    flex: 1,
    fontFamily: Fonts.Gilroy,
    fontSize: respFontSize(15),
    paddingVertical: responsiveSize(5),
    color: Colors.white,
  },
  arrowRightTouchStyles: { alignSelf: 'center' },
  arrowRight: { height: responsiveSize(15), width: responsiveSize(20) },
  keyboardContentContainerStyle: { flex: 1 },
  optionButton: {
    borderWidth: 1,
    paddingHorizontal: responsiveSize(18),
    paddingVertical: responsiveSize(5),
    borderColor: Colors.darkSilver,
    borderRadius: responsiveSize(10),
  },
  buttonWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: responsiveSize(10),
    paddingHorizontal: responsiveSize(8),
  },
  buttonText: {
    fontFamily: Fonts.GilroyMedium,
    color: Colors.white,
    lineHeight: responsiveSize(20),
    fontSize: respFontSize(14),
    textAlign: 'center',
  },
  modalParentView: {
    marginHorizontal: responsiveSize(40),
    paddingVertical: responsiveSize(40),
  },
  radioButton: {
    borderRadius: responsiveSize(10),
    width: responsiveSize(20),
    height: responsiveSize(20),
    borderWidth: 1,
    borderColor: Colors.silver,
  },
  optionModalHeading: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(15),
    marginBottom: responsiveSize(20),
  },
  optionsText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(14),
    paddingVertical: responsiveSize(12),
  },
  rowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
  },
  selectedImageStyles: {
    width: '95%',
    aspectRatio: 1,
    resizeMode: 'contain',
  },
  imageWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  sendImgModalContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: Colors.secondary,
  },
})
