import { StyleSheet } from 'react-native'

import { responsiveSize, Colors, respFontSize, Fonts } from '@/Utils'

export const styles = StyleSheet.create({
  pressableStyles: {
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Colors.lightBlack,
    width: responsiveSize(125),
    height: responsiveSize(28),
    borderRadius: responsiveSize(5),
    borderWidth: 1,
  },
  buttonText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(12),
  },
  confirmationText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyBold,
    fontSize: respFontSize(14),
  },
  buttonWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: responsiveSize(20),
    width: '80%',
  },
  imgStyles: {
    top: responsiveSize(25),
    justifyContent: 'center',
    alignItems: 'center',
    height: responsiveSize(86),
    width: responsiveSize(86),
    borderRadius: responsiveSize(43),
    backgroundColor: Colors.primary,
    zIndex: 2,
  },
  lockStyles: {
    resizeMode: 'contain',
    width: responsiveSize(33),
    height: responsiveSize(41),
  },
  lockedSubscriptionCard: {
    borderColor: Colors.primary,
    borderWidth: 1,
    borderRadius: responsiveSize(12),
    height: responsiveSize(170),
    width: responsiveSize(396),
    backgroundColor: Colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: responsiveSize(5),
  },
  cardContainerStyle: {
    marginTop: responsiveSize(107),
    borderColor: Colors.primary,
    borderRadius: responsiveSize(12),
    backgroundColor: Colors.secondary,
    borderWidth: 1,
    height: responsiveSize(107),
    width: responsiveSize(328),

    justifyContent: 'center',
    alignItems: 'center',
  },
  subToChannelText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyBold,
    fontSize: respFontSize(13),
    textAlign: 'center',
  },
  subscribeButton: {
    marginTop: responsiveSize(16),
    width: responsiveSize(131),
    height: responsiveSize(28),
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: responsiveSize(5),
  },
  subscribeText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(12),
  },
  gotoChannelBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    marginTop: responsiveSize(16),
    height: responsiveSize(28),
    width: responsiveSize(131),
    borderRadius: responsiveSize(5),
  },
  gotoChannelText: {
    color: Colors.lightBlack,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(12),
  },
  mainContainer: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: responsiveSize(50),
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerContainer: { alignItems: 'center' },
})
