export const endpoints = {
  check_username: 'user/check-username/',
  register: 'user/user-profile/',
  login: 'user/login/',
  logout: 'user/logout/',
  reset_password: 'user/reset-password/',
  change_password: 'user/change-password/',
  user_send_otp: 'user/send-otp/',
  user_verify_otp: 'user/verify-otp/',
  user_delete_profile: 'user/delete-profile/',

  common: {
    Terms_And_Conditions: 'common/terms-cond/',
    get_category: 'common/get-list/',
    get_email_otp: 'common/get-otp/',
    verify_otp: 'common/verify-otp/',
    privacy_policy: 'common/privacy-policy/',
    faq: 'common/faq/',
    contact_us: 'common/contact-us/',
    panCard: 'common/pan-verify/',
    bankVerify: 'common/bank-verify/?',
    kycStatus: 'common/kyc-status/',
    reportThread: 'common/reported-thread-status/',
    blockUser: 'common/block-user/',
    reportMessage: 'common/reported-message-status/',
    beneficiaryDetails: 'common/get-user-account-no/',
    transferPayout: 'common/transfer-money-ios/',
    toggleNotification: 'common/update-notification-status/',
  },
  channel: 'channel/channel/',
  channel_details: 'channel/channel-detail/',
  popular_channels: 'channel/popular-channel-detail/',
  follow_unfollow: 'channel/channel-follower/',
  followed_channels: 'channel/user-follow-channel-detail/',
  popular_with_category: 'channel/best_rated_sports_category/',
  create_thread: 'chat/thread/',
  community_announcement: 'chat/community-announcement/',
  about_us: 'chat/about-us/',
  create_announcement_status: 'chat/create-announcement-status/',
  another_user_detail: 'user/get-user-profile-detail/',
  another_user_channel_detail: 'channel/get-another-user-channel-detail/',
  wallet: 'subscription/coins-ios/',
  subscribeChannel: 'subscription/channel-subscribe-ios/',
  chat_update_thread_message_status: 'chat/update-thread-message-status/',
}
