import { Platform, StyleSheet } from 'react-native'

import {
  responsiveSize,
  Colors,
  respFontSize,
  Fonts,
  height,
  width,
} from '@/Utils'

const MODAL_TOP = Platform.OS === 'ios' ? 3 : 4

export const styles = StyleSheet.create({
  mainContainer: { backgroundColor: Colors.secondary, flex: 1 },
  itemSeparatorComponent: { height: responsiveSize(26) },
  threadNameView: {
    alignSelf: 'center',
    alignItems: 'center',
    marginVertical: responsiveSize(20),
    borderBottomColor: Colors.darkSilver,
    borderBottomWidth: 1,
  },
  threadNameText: {
    maxWidth: responsiveSize(350),
    color: Colors.white,
    fontFamily: Fonts.GilroyBold,
    fontSize: respFontSize(15),
    marginBottom: responsiveSize(10),
  },
  flatListView: {
    // flex: 1,
  },
  parentContainer: {
    width: responsiveSize(385),
    alignSelf: 'flex-end',
    flexDirection: 'row',
  },
  Container: {
    borderTopLeftRadius: responsiveSize(8),
    borderBottomLeftRadius: responsiveSize(8),
    borderBottomRightRadius: responsiveSize(8),
    backgroundColor: Colors.messageCardGrey,
    padding: responsiveSize(20),
    flex: 1,
  },
  repliedView: {
    padding: responsiveSize(10),
    borderColor: Colors.primary,
    borderWidth: 1,
    borderRadius: responsiveSize(7),
  },
  textMessage: {
    fontFamily: Fonts.GilroyMedium,
    color: Colors.silver,
    lineHeight: responsiveSize(25),
    fontSize: respFontSize(15),
    marginTop: responsiveSize(5),
  },
  currentUserTitle: {
    fontFamily: Fonts.GilroyBold,
    color: Colors.primary,
    fontSize: respFontSize(15),
  },
  noteMessage: {
    fontFamily: Fonts.GilroyBold,
    color: Colors.primary,
    lineHeight: responsiveSize(20),
    fontSize: respFontSize(15),
  },
  rightTriangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: responsiveSize(13),
    borderRightWidth: responsiveSize(13),
    borderBottomWidth: responsiveSize(26),
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.messageCardGrey,
    transform: [{ rotate: '90deg' }],
    marginLeft: responsiveSize(-1),
  },
  dateView: {
    alignSelf: 'flex-end',
    backgroundColor: Colors.messageCardGrey,
    paddingTop: responsiveSize(5),
  },
  dateText: {
    color: Colors.white,
    fontFamily: Fonts.Gilroy,
    fontSize: respFontSize(9),
  },
  flatListStyles: { paddingTop: responsiveSize(10) },
  textInputView: {
    marginTop: responsiveSize(10),
    marginBottom: responsiveSize(10),
    marginHorizontal: responsiveSize(20),
    justifyContent: 'space-between',
    paddingHorizontal: responsiveSize(25),
    maxHeight: responsiveSize(140),
    borderWidth: 1,
    borderRadius: responsiveSize(20),
    borderColor: Colors.messageCardGrey,
    flexDirection: 'row',
    padding: responsiveSize(5),
  },
  textInputStyles: {
    flex: 1,
    fontFamily: Fonts.Gilroy,
    fontSize: respFontSize(15),
    paddingVertical: responsiveSize(5),
    color: Colors.white,
  },
  arrowRightTouchStyles: { alignSelf: 'center' },
  arrowRight: { height: responsiveSize(15), width: responsiveSize(20) },
  keyboardContentContainerStyle: { flex: 1 },
  transparentPressable: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
  },
  announcementContentView: {
    zIndex: 99,
    position: 'absolute',
    height: responsiveSize(360),
    width: responsiveSize(430),
    backgroundColor: Colors.lightBlack,
    padding: responsiveSize(30),
    borderRadius: responsiveSize(20),
    top: height / MODAL_TOP,
    left: width - (width - 20),
  },
  backIcon: {
    width: responsiveSize(25),
    resizeMode: 'contain',
    height: responsiveSize(25),
  },
  postButton: {
    width: '100%',
    backgroundColor: Colors.primary,
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: responsiveSize(8),
    marginTop: responsiveSize(30),
  },
  postText: {
    fontSize: respFontSize(16),
    color: Colors.white,
    fontFamily: Fonts.GilroyBold,
    padding: responsiveSize(14),
  },
  modalParentView: {
    marginHorizontal: responsiveSize(40),
    paddingVertical: responsiveSize(40),
  },
  radioButton: {
    borderRadius: responsiveSize(10),
    width: responsiveSize(20),
    height: responsiveSize(20),
    borderWidth: 1,
    borderColor: Colors.silver,
  },
  optionModalHeading: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(15),
    marginBottom: responsiveSize(20),
  },
  optionsText: {
    color: Colors.white,
    fontFamily: Fonts.GilroyMedium,
    fontSize: respFontSize(14),
    paddingVertical: responsiveSize(12),
  },
  rowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
  },
  pin: {
    height: responsiveSize(20),
    width: responsiveSize(20),
    marginRight: responsiveSize(5),
  },
  iconsView: {
    height: responsiveSize(60),
    width: responsiveSize(60),
  },
  iconsContainer: {
    flexDirection: 'row',
    // justifyContent: 'space-around'
  },
  modalCameraParentView: {
    margin: responsiveSize(40),
  },
  modalText: {
    fontSize: respFontSize(11),
    fontFamily: Fonts.GilroyMedium,
    color: Colors.silver,
    marginTop: responsiveSize(10),
  },
  imageWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },

  selectedImageStyles: {
    width: '95%',
    aspectRatio: 1,
    resizeMode: 'contain',
  },
  sendImagePressableStyles: {
    alignSelf: 'flex-end',
    backgroundColor: Colors.primary,
    borderRadius: responsiveSize(50),
    padding: responsiveSize(10),
    marginRight: responsiveSize(35),
    marginBottom: responsiveSize(25),
  },
  arrowRightImgStyles: {
    height: responsiveSize(35),
    width: responsiveSize(35),
    resizeMode: 'contain',
    tintColor: Colors.white,
  },
  sendImgModalContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: Colors.secondary,
  },
})
